name: Build DcRat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/7b3e8dc1-8159-4e05-b70b-9274dc92a3e3/2B665D3E955AEAB741F62E845C5102F0708F87BF71AC95F482CFC76A3C0C8A39/ndp472-devpack-enu.exe" -OutFile "ndp472-devpack-enu.exe"
        Start-Process .\ndp472-devpack-enu.exe -ArgumentList "/quiet", "/norestart" -Wait
      
    # Install 7Zip PowerShell Module
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose

    # Add MSBuild to the PATH
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # Install NuGet packages
    - name: Install NuGet Packages
      run: nuget restore DcRat.sln

    # Build solution
    - name: Build solution
      run: msbuild -nologo -v:m -p:Configuration=${{ matrix.configuration }} DcRat.sln
        
    # Build Artifact
    - name: Build Artifact
      shell: cmd
      run: call .\ArtifactBuild.cmd
      
    # Delete-tag-and-release
    - name: Delete-tag-and-release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true # default: false
        tag_name: AutoBuild # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Create Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: AutoBuild
        release_name: AutoBuild
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: true
        
    # Upload Release Asset
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./DcRat.zip
        asset_name: DcRat.zip
        asset_content_type: application/zip
